
package clienteP3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ToUpperService", targetNamespace = "http://upperCase/", wsdlLocation = "file:/home/giuly/Escritorio/Distribuidos_Compartido/Sist_distribuidos/ssdd_pract_material/Parte3/Mayusculas.wsdl")
public class ToUpperService
    extends Service
{

    private final static URL TOUPPERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOUPPERSERVICE_EXCEPTION;
    private final static QName TOUPPERSERVICE_QNAME = new QName("http://upperCase/", "ToUpperService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/giuly/Escritorio/Distribuidos_Compartido/Sist_distribuidos/ssdd_pract_material/Parte3/Mayusculas.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOUPPERSERVICE_WSDL_LOCATION = url;
        TOUPPERSERVICE_EXCEPTION = e;
    }

    public ToUpperService() {
        super(__getWsdlLocation(), TOUPPERSERVICE_QNAME);
    }

    public ToUpperService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOUPPERSERVICE_QNAME, features);
    }

    public ToUpperService(URL wsdlLocation) {
        super(wsdlLocation, TOUPPERSERVICE_QNAME);
    }

    public ToUpperService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOUPPERSERVICE_QNAME, features);
    }

    public ToUpperService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ToUpperService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ToUpper
     */
    @WebEndpoint(name = "ToUpperPort")
    public ToUpper getToUpperPort() {
        return super.getPort(new QName("http://upperCase/", "ToUpperPort"), ToUpper.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ToUpper
     */
    @WebEndpoint(name = "ToUpperPort")
    public ToUpper getToUpperPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://upperCase/", "ToUpperPort"), ToUpper.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOUPPERSERVICE_EXCEPTION!= null) {
            throw TOUPPERSERVICE_EXCEPTION;
        }
        return TOUPPERSERVICE_WSDL_LOCATION;
    }

}
