
package clienteP3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ToUpper", targetNamespace = "http://upperCase/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ToUpper {


    /**
     * 
     */
    @WebMethod(operationName = "ToUpper")
    @RequestWrapper(localName = "ToUpper", targetNamespace = "http://upperCase/", className = "clienteP3.ToUpper_Type")
    @ResponseWrapper(localName = "ToUpperResponse", targetNamespace = "http://upperCase/", className = "clienteP3.ToUpperResponse")
    @Action(input = "http://upperCase/ToUpper/ToUpperRequest", output = "http://upperCase/ToUpper/ToUpperResponse")
    public void toUpper();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Upper")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Upper", targetNamespace = "http://upperCase/", className = "clienteP3.Upper")
    @ResponseWrapper(localName = "UpperResponse", targetNamespace = "http://upperCase/", className = "clienteP3.UpperResponse")
    @Action(input = "http://upperCase/ToUpper/UpperRequest", output = "http://upperCase/ToUpper/UpperResponse")
    public String upper(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
